In [81]:
import pandas as pd
import numpy as np
import yfinance as yf
import os
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

In [82]:
os.makedirs("../data/raw", exist_ok=True)
os.makedirs("../data/processed", exist_ok=True)

In [83]:
START = "2015-01-01"
END = "2026-06-30"

tickers = ["TSLA", "SPY", "BND"]

datasets = {}

for ticker in tickers:

    print(f"Downloading {ticker}...")

    df = yf.download(
        ticker,
        start=START,
        end=END,
        auto_adjust=False,
        progress=False
    )

    # Fix MultiIndex columns (new yfinance)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df.reset_index(inplace=True)

    datasets[ticker] = df

    df.to_csv(f"../data/raw/{ticker}.csv", index=False)

print("Download Completed")

Downloading TSLA...
Downloading SPY...
Downloading BND...
Download Completed

In [84]:
tsla = pd.read_csv("../data/raw/TSLA.csv")
spy = pd.read_csv("../data/raw/SPY.csv")
bnd = pd.read_csv("../data/raw/BND.csv")

In [85]:
print(tsla.head())

         Date  Adj Close      Close       High        Low       Open    Volume
0  2015-01-02  14.620667  14.620667  14.883333  14.217333  14.858000  71466000
1  2015-01-05  14.006000  14.006000  14.433333  13.810667  14.303333  80527500
2  2015-01-06  14.085333  14.085333  14.280000  13.614000  14.004000  93928500
3  2015-01-07  14.063333  14.063333  14.318667  13.985333  14.223333  44526000
4  2015-01-08  14.041333  14.041333  14.253333  14.000667  14.187333  51637500

In [86]:
print(spy.head())

         Date   Adj Close       Close        High         Low        Open  \
0  2015-01-02  169.687851  205.429993  206.880005  204.179993  206.380005
1  2015-01-05  166.623337  201.720001  204.369995  201.350006  204.169998
2  2015-01-06  165.053894  199.820007  202.720001  198.860001  202.089996
3  2015-01-07  167.110703  202.309998  202.720001  200.880005  201.419998
4  2015-01-08  170.076019  205.899994  206.160004  203.990005  204.009995

      Volume
0  121465900
1  169632600
2  209151400
3  125346700
4  147217800

In [87]:
print(bnd.head())

         Date  Adj Close      Close       High        Low       Open   Volume
0  2015-01-02  59.405460  82.650002  82.690002  82.419998  82.430000  2218800
1  2015-01-05  59.577934  82.889999  82.919998  82.699997  82.739998  5820100
2  2015-01-06  59.750439  83.129997  83.379997  83.029999  83.029999  3887600
3  2015-01-07  59.786346  83.180000  83.279999  83.050003  83.139999  2433400
4  2015-01-08  59.692909  83.050003  83.110001  82.970001  83.110001  1873400

In [88]:
tsla["Date"] = pd.to_datetime(tsla["Date"])
spy["Date"] = pd.to_datetime(spy["Date"])
bnd["Date"] = pd.to_datetime(bnd["Date"])

In [89]:
tsla.set_index("Date", inplace=True)
spy.set_index("Date", inplace=True)
bnd.set_index("Date", inplace=True)

In [90]:
tsla.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2888 entries, 2015-01-02 to 2026-06-29
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  2888 non-null   float64
 1   Close      2888 non-null   float64
 2   High       2888 non-null   float64
 3   Low        2888 non-null   float64
 4   Open       2888 non-null   float64
 5   Volume     2888 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 157.9 KB

In [91]:
spy.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2888 entries, 2015-01-02 to 2026-06-29
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  2888 non-null   float64
 1   Close      2888 non-null   float64
 2   High       2888 non-null   float64
 3   Low        2888 non-null   float64
 4   Open       2888 non-null   float64
 5   Volume     2888 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 157.9 KB

In [92]:
bnd.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2888 entries, 2015-01-02 to 2026-06-29
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  2888 non-null   float64
 1   Close      2888 non-null   float64
 2   High       2888 non-null   float64
 3   Low        2888 non-null   float64
 4   Open       2888 non-null   float64
 5   Volume     2888 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 157.9 KB

In [93]:
tsla.describe()

,Adj Close,Close,High,Low,Open,Volume
count,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2.888000e+03
mean,148.773923,148.773923,151.990563,145.416731,148.797341,1.087922e+08
std,138.895957,138.895957,141.852818,135.867193,138.977191,7.082549e+07
min,9.578000,9.578000,10.331333,9.403333,9.488000,1.062000e+07
25%,18.393499,18.393499,18.665168,18.023666,18.390833,6.548325e+07
50%,133.437668,133.437668,136.053329,125.831669,131.496330,9.033615e+07
75%,251.925831,251.925831,257.485008,245.832500,251.680004,1.261204e+08
max,489.880005,489.880005,498.829987,485.329987,489.880005,9.140820e+08

In [94]:
spy.describe()

,Adj Close,Close,High,Low,Open,Volume
count,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2.888000e+03
mean,351.505531,375.216714,377.167216,372.946586,375.149543,8.551049e+07
std,155.443935,146.584697,147.244714,145.774814,146.558911,4.338553e+07
min,154.161606,182.860001,184.100006,181.020004,182.339996,2.027000e+07
25%,223.546841,254.559998,255.919998,252.477497,254.577503,5.836455e+07
50%,312.817917,339.435013,342.315002,337.165009,339.835007,7.541950e+07
75%,432.806870,453.677498,456.000000,451.549988,453.989990,9.882245e+07
max,757.618225,759.570007,760.400024,756.750000,758.150024,5.072443e+08

In [95]:
bnd.describe()

,Adj Close,Close,High,Low,Open,Volume
count,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2.888000e+03
mean,66.503052,79.327722,79.442119,79.211198,79.330661,4.653786e+06
std,4.713606,5.310424,5.298010,5.322546,5.313805,3.017704e+06
min,58.729229,68.040001,68.379997,67.989998,68.080002,0.000000e+00
25%,62.478062,73.800003,73.919998,73.639999,73.800003,2.233700e+06
50%,65.728390,80.814999,80.905003,80.709999,80.800003,4.280650e+06
75%,70.689133,83.440002,83.550003,83.332500,83.470001,6.246475e+06
max,74.832893,89.480003,89.589996,89.440002,89.550003,3.396300e+07

In [96]:
print(tsla.isnull().sum())

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [97]:
print(spy.isnull().sum())

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [98]:
print(bnd.isnull().sum())

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [99]:
tsla = tsla.ffill().bfill()
spy = spy.ffill().bfill()
bnd = bnd.ffill().bfill()

In [100]:
tsla["Daily Return"] = tsla["Close"].pct_change()

spy["Daily Return"] = spy["Close"].pct_change()

bnd["Daily Return"] = bnd["Close"].pct_change()

In [101]:
tsla["Rolling Mean"] = tsla["Close"].rolling(30).mean()
tsla["Rolling Std"] = tsla["Close"].rolling(30).std()

spy["Rolling Mean"] = spy["Close"].rolling(30).mean()
spy["Rolling Std"] = spy["Close"].rolling(30).std()

bnd["Rolling Mean"] = bnd["Close"].rolling(30).mean()
bnd["Rolling Std"] = bnd["Close"].rolling(30).std()

In [102]:
tsla.to_csv("../data/processed/TSLA_processed.csv")

spy.to_csv("../data/processed/SPY_processed.csv")

bnd.to_csv("../data/processed/BND_processed.csv")

In [103]:
import os

print(os.listdir("../data/processed"))

['BND_processed.csv', 'SPY_processed.csv', 'TSLA_processed.csv']